// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: batch.go

package db

import (
	"context"
	"errors"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const upgradeUsersToRound = `-- name: UpgradeUsersToRound :batchexec
UPDATE users
SET round_qualified = GREATEST(round_qualified, $2)
WHERE id = $1
`

type UpgradeUsersToRoundBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type UpgradeUsersToRoundParams struct {
	ID             uuid.UUID
	RoundQualified int32
}

func (q *Queries) UpgradeUsersToRound(ctx context.Context, arg []UpgradeUsersToRoundParams) *UpgradeUsersToRoundBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ID,
			a.RoundQualified,
		}
		batch.Queue(upgradeUsersToRound, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UpgradeUsersToRoundBatchResults{br, len(arg), false}
}

func (b *UpgradeUsersToRoundBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *UpgradeUsersToRoundBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
