// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: submission_status.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSubmissionStatus = `-- name: CreateSubmissionStatus :exec
INSERT INTO submission_results (id, submission_id, runtime, memory, description)
VALUES ($1, $2, $3, $4, $5)
`

type CreateSubmissionStatusParams struct {
	ID           uuid.UUID
	SubmissionID uuid.UUID
	Runtime      pgtype.Numeric
	Memory       pgtype.Numeric
	Description  *string
}

func (q *Queries) CreateSubmissionStatus(ctx context.Context, arg CreateSubmissionStatusParams) error {
	_, err := q.db.Exec(ctx, createSubmissionStatus,
		arg.ID,
		arg.SubmissionID,
		arg.Runtime,
		arg.Memory,
		arg.Description,
	)
	return err
}
